# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('workspace_write', 'Write file to workspace'), ('workspace_read', 'Read file from workspace'), ('shell', 'Sandboxed shell command'), ('http', 'HTTP fetch'), ('builtin', 'Built-in function')], default='builtin', max_length=40)),
                ('handler', models.CharField(blank=True, help_text='Dotted path to the registered handler in core.tools.', max_length=200)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global/system tool available to every org.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
