# Generated by Django 5.0.6 on 2026-08-09 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


def attach_legacy_workflows(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Workflow = apps.get_model('workflows', 'Workflow')
    for project in Project.objects.exclude(workflow_id=None).iterator():
        Workflow.objects.filter(pk=project.workflow_id, workspace_id=None).update(workspace_id=project.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='projects.project'),
        ),
        migrations.RunPython(attach_legacy_workflows, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#9b5f34', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='organizations.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='workflows.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
                'unique_together': {('workflow', 'name')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='workflows.arena'),
        ),
        migrations.CreateModel(
            name='WorkflowLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('related', 'Related'), ('depends_on', 'Depends on'), ('triggers', 'Triggers'), ('subworkflow', 'Subworkflow')], default='related', max_length=30)),
                ('condition', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_links', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_workflow_links', to='workflows.workflow')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_workflow_links', to='workflows.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_links', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('source', 'target', 'kind')},
            },
        ),
    ]
