# Generated by Django 5.0.6 on 2026-08-09 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_title_knowledgesource'),
        ('organizations', '0001_initial'),
        ('projects', '0002_task_acceptance_criteria_task_due_at_task_issue_type_and_more'),
        ('workflows', '0002_workflow_workspace_arena_node_arena_workflowlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('namespace', models.SlugField(default='default', max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('importance', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='agents.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='organizations.organization')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='workflows.workflow')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'namespace', 'importance'], name='agents_memo_organiz_9da04b_idx')],
                'unique_together': {('organization', 'namespace', 'key')},
            },
        ),
    ]
