# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('adapter', models.CharField(choices=[('fake', 'Fake (deterministic, offline)'), ('openai_responses', 'OpenAI Responses API'), ('openai_compatible', 'OpenAI-compatible Chat Completions'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('azure_openai', 'Azure OpenAI / Foundry'), ('bedrock', 'Amazon Bedrock'), ('vertex', 'Google Vertex AI'), ('cohere', 'Cohere'), ('replicate', 'Replicate Predictions'), ('cloudflare', 'Cloudflare Workers AI'), ('generic_rest', 'Configurable REST')], default='fake', max_length=40)),
                ('base_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_providers', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=120)),
                ('remote_id', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(max_length=150)),
                ('context_window', models.PositiveIntegerField(default=8192)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='organizations.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='models_registry.modelprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(default='default', max_length=120)),
                ('_secret', models.TextField(blank=True, db_column='secret_encrypted')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='models_registry.modelprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('provider', 'label')},
            },
        ),
    ]
