# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('executions', '0001_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('spec', 'Specification'), ('code', 'Source code'), ('test', 'Test / report'), ('diagram', 'Diagram'), ('data', 'Data'), ('other', 'Other')], default='document', max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(default='text/plain', max_length=100)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='executions.noderun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='organizations.organization')),
                ('produced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='actors.actor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'kind'], name='artifacts_a_project_da4776_idx')],
            },
        ),
    ]
