# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('budget', 'Budget cap'), ('tool_access', 'Tool access'), ('approval', 'Approval required'), ('rate_limit', 'Rate limit'), ('data_access', 'Data access')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='organizations.organization')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'abstract': False,
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
