# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('prompts', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('waiting_for_approval', 'Waiting for Approval'), ('paused', 'Paused'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('stop_reason', models.CharField(blank=True, max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('scenario', models.CharField(default='fail_once', help_text='Drives the deterministic FakeModelProvider (fail_once/success/always_fail).', max_length=40)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='projects.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoopState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('max_iterations', models.PositiveIntegerField(default=5)),
                ('max_duration_seconds', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('failure_threshold', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('pass', 'Passed'), ('max_iterations', 'Max iterations'), ('max_cost', 'Max cost'), ('max_time', 'Max time'), ('manual_stop', 'Manual stop'), ('fatal_error', 'Fatal error'), ('rejected', 'Rejected')], max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_states', to='executions.execution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_states', to='workflows.node')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('node_key', models.CharField(blank=True, max_length=100)),
                ('node_type', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('model_key', models.CharField(blank=True, max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='executions.execution')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='workflows.node')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_runs', to='prompts.promptversion')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_runs', to='projects.task')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['organization', 'status'], name='executions__organiz_75543c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loopstate',
            unique_together={('execution', 'node')},
        ),
        migrations.AddIndex(
            model_name='noderun',
            index=models.Index(fields=['execution', 'status'], name='executions__executi_fdbfd1_idx'),
        ),
    ]
