# Generated by Django 5.0.6 on 2026-08-09 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('executions', '0001_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0002_task_acceptance_criteria_task_due_at_task_issue_type_and_more'),
        ('workflows', '0002_workflow_workspace_arena_node_arena_workflowlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('approval', 'Approval'), ('human_task', 'Human task'), ('operator', 'Operator intervention')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='actors.actor')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='executions.execution')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='workflows.node')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_interventions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_interventions', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention', to='projects.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'status'], name='executions__organiz_5dcd04_idx'), models.Index(fields=['execution', 'node', 'iteration'], name='executions__executi_6ab997_idx')],
            },
        ),
    ]
