# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('executions', '0001_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_work', 'Needs Work')], default='fail', max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('tests_passed', models.BooleanField(default=False)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('tests_failed', models.PositiveIntegerField(default=0)),
                ('requirement_coverage', models.FloatField(default=0.0, help_text='0.0 – 1.0')),
                ('critical_errors', models.PositiveIntegerField(default=0)),
                ('coverage_threshold', models.FloatField(default=0.8)),
                ('score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True, help_text='Actionable feedback fed into the fix task.')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('evaluator_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='actors.actor')),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='executions.noderun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'iteration'], name='evaluations_project_178f5b_idx')],
            },
        ),
    ]
