# Generated by Django 5.0.6 on 2026-08-09 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('organizations', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('ai_agent', 'AI Agent'), ('hybrid', 'Hybrid'), ('system', 'System')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('presence', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('working', 'Working'), ('offline', 'Offline')], default='available', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor', to='agents.agent')),
                ('capabilities', models.ManyToManyField(blank=True, related_name='actors', to='structure.capability')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='actors.actor')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='structure.role')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['organization', 'kind'], name='actors_acto_organiz_9cc6ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('actor', 'role')},
        ),
    ]
